import type { Metadata } from "next";
import { Sidebar } from "@/components/Sidebar";
import { Header } from "@/components/Header";


export const metadata: Metadata = {
  title: "DashBoard",
  description: "Generated by create next app",
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex h-screen">
        <aside className="hidden md:flex w-72 flex-col fixed inset-y-0 z-50 border-r">
          <Sidebar />
        </aside>
        <div className="md:pl-72 flex-1">
          <Header />
          <main className="flex-1 p-6">{children}</main>
        </div>
      </div>
    </>
  );
}
